#!/bin/bash

sm2 --start EMAIL GATEKEEPER_EMAIL DEVELOPER_EMAIL_RENDERER
sm2 --start DATASTREAM AUTH AUTH_LOGIN_API AUTH_LOGIN_STUB TIME_BASED_ONE_TIME_PASSWORD STRIDE_AUTH_FRONTEND STRIDE_AUTH STRIDE_IDP_STUB  USER_DETAILS

sm2 --start API_PUBLISHER UPSCAN_STUB MAILGUN_STUB UPLOAD_DOCUMENTS_ALL

./run_local.sh
